### PR TITLE
Update smilegupta.md

### PR DESCRIPTION
**Pull request by sanjana001**
I have tried to make something from my side.

### CODE REVIEW

**Comment by sanjana001** [comment]
Please check it if there is something that we should add.

**Comment by smilegupta** [comment]
@Sanjana001 Make a new file named Sanjana.md file and add all the content in that file. For example! Your name date and all the things. Plus the links i had added just one! you have to add all 5 ones which we discussed in class

**Review by smilegupta — CHANGES_REQUESTED** [review]
Make a new file named Sanjana.md file and add all the content in that file. For example! Your name date and all the things. Plus the links i had added just one! you have to add all 5 ones which we discussed in class

**Comment by sanjana001** [comment]
OK I'll do that

**Comment by sanjana001** [comment]
Check it now mam.

**Review by smilegupta — APPROVED** [review]

**Comment by smilegupta** [comment]
@Sanjana001 Merged it! Good work done.

**Comment by smilegupta** [comment]
Btw if you got time, I have improved  your readme file a bit and added a way to do hyperlinking in the readme file/Markdown file. If had any doubts regarding why and what I did. Let me know.

Rest Here is [Link](https://del.dog/react-day2.txt) for day 2. You have  a look in it before hand itself.

**Pull request merged**
